name: Deploy LegendaryCruises

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish
        run: dotnet publish ./LegendaryCruises.csproj -c Release -o ./publish

      - name: Create ZIP package
        run: cd publish && zip -r ../publish.zip .

      - name: Deploy to Azure WebApp (ZIP Deploy)
        uses: azure/webapps-deploy@v2
        with:
          app-name: worldcruises
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: publish.zip
